language: erlang
notifications:
  email: false
otp_release:
  - 21.1
  - 20.3.8
matrix:
  include:
  - otp_release: 19.3.6
    dist: trusty
  - otp_release: 18.3
    dist: trusty
  - otp_release: 17.5
    dist: trusty
  - otp_release: R16B03-1
    dist: trusty
  - otp_release: R15B03
    dist: trusty
script: rebar compile && rebar eunit
